#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import base64
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.

APP_URL = data.get("host", "")
app = {
    "APP_URL": "https://"+APP_URL,
}

agent.write_envfile("app.env", app)

#agent.dump_env()
