#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import base64
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# we read a json stdin {"vars1":true, "var2":"foo", "vars3": 3} and we writ it to .config/state/environment
# Setup database
POSTGRES_USER= data.get("POSTGRES_USER", "postgres")
POSTGRES_PASSWORD= data.get("POSTGRES_PASSWORD", "Nethesis@1234")
POSTGRES_DB= data.get("POSTGRES_DB", "firefly")

db = {
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
    "POSTGRES_DB": POSTGRES_DB,
}
agent.write_envfile("database.env", db)


random_bytes = os.urandom(32)
base64_bytes = base64.b64encode(random_bytes)
base64_message = base64_bytes.decode('utf-8')
APP_KEY = "base64:" + base64_message
DB_HOST="postgresql-app"
DB_USERNAME=POSTGRES_USER
DB_PASSWORD=POSTGRES_PASSWORD
APP_URL = data.get("host", "")
app = {
    "APP_KEY": APP_KEY,
    "DB_HOST": DB_HOST,
    "DB_USERNAME": DB_USERNAME,
    "DB_PASSWORD": DB_PASSWORD,
    "DB_DATABASE": POSTGRES_DB,
    "APP_URL": "https://"+APP_URL,
    "DB_CONNECTION": "pgsql",
    "DB_PORT": "5432",
    "TRUSTED_PROXIES": "*",
}

agent.write_envfile("app.env", app)

#agent.dump_env()
