#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import base64
import os
import secrets

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

def generate_random_password():
    return secrets.token_urlsafe(16)

# Setup database
POSTGRES_USER= data.get("POSTGRES_USER", "postgres")
POSTGRES_PASSWORD= generate_random_password()
POSTGRES_DB= data.get("POSTGRES_DB", "firefly")

db = {
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
    "POSTGRES_DB": POSTGRES_DB,
}
agent.write_envfile("database.env", db)

def generate_app_key():
    random_bytes = os.urandom(32)
    base64_bytes = base64.b64encode(random_bytes)
    base64_message = base64_bytes.decode('utf-8')
    return "base64:" + base64_message

APP_KEY= generate_app_key()
DB_HOST="postgresql-app"
DB_USERNAME=POSTGRES_USER
DB_PASSWORD=POSTGRES_PASSWORD
app = {
    "APP_KEY": APP_KEY,
    "DB_HOST": DB_HOST,
    "DB_USERNAME": DB_USERNAME,
    "DB_PASSWORD": DB_PASSWORD,
    "DB_DATABASE": POSTGRES_DB,
    "DB_CONNECTION": "pgsql",
    "DB_PORT": "5432",
    "TRUSTED_PROXIES": "*",
}

agent.write_envfile("app-db.env", app)

#agent.dump_env()
